<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Design2VisitorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Design2VisitorRepository extends EntityRepository
{

    /**
     * SELECT * FROM `design2visitor` as d inner join visitor as v on d.visitor_id = v.id inner join file as f on d.file_id = f.id where v.s_name = 'Хомюк'
     */
    public  function search($docNum,$sName,$startDate,$endDate){
        
        $params = [];
        
       $qb =  $this->createQueryBuilder('d')
            ->select('v as visitor, f.number as fileNumber ,tv.typeName as typeName ,dc.type as docType')
            ->innerJoin('AppBundle:Visitor', 'v', 'WITH', 'v.id = d.visitorId')
            ->innerJoin('AppBundle:File', 'f', 'WITH', 'f.id = d.fileId')
            ->innerJoin('AppBundle:TypeVisitor', 'tv', 'WITH', 'tv.id = v.typeVisitorId')
             ->innerJoin('AppBundle:Document', 'dc', 'WITH', 'dc.id = v.typeVisitorId');
        if($docNum){
            $qb->where('f.number = :docNum');
            $params['docNum'] = $docNum;
        }
        if($sName){
            $qb->andWhere('v.sName = :sName');
            $params['sName'] = $sName;
        }
        if($startDate){
            $qb->andWhere('d.dateCreated > :starDate')
                ->andWhere('d.dateCreated < :endDate');
            $params['starDate'] = $startDate;
            $params['endDate'] = $endDate;
        }
        
      return  $qb->setParameters($params)
            ->getQuery()
            ->getResult();
                    
    }
}
