<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Design2VisitorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Design2VisitorRepository extends EntityRepository
{

    /**
     * @param $docNum
     * @param $sName
     * @param $startDate \DateTime
     * @param $endDate \DateTime
     * @return array
     */
    public  function search($docNum,$sName,$startDate,$endDate){
        
        $params = [];
        
       $qb =  $this->createQueryBuilder('d')
            ->select('v as visitor, f.number as fileNumber ,tv.typeName as typeName ,dc.type as docType')
            ->innerJoin('AppBundle:Visitor', 'v', 'WITH', 'v.id = d.visitorId')
            ->innerJoin('AppBundle:File', 'f', 'WITH', 'f.id = v.typeDocId')
            ->innerJoin('AppBundle:TypeVisitor', 'tv', 'WITH', 'tv.id = v.typeVisitorId')
             ->innerJoin('AppBundle:Document', 'dc', 'WITH', 'dc.id = v.typeDocId');
        if($docNum){
            $qb->where('f.number = :docNum');
            $params['docNum'] = $docNum;
        }
        if($sName){
            $qb->andWhere('v.sName = :sName');
            $params['sName'] = $sName;
        }
        if($startDate){
            $qb->andWhere('d.dateCreated  >= :starDate')
                ->andWhere('d.dateCreated <= :endDate');
            $params['starDate'] = $startDate->format('Y-m-d');
            $params['endDate'] = $endDate->format('Y-m-d 23:59:59');
        }
        
      return  $qb->setParameters($params)
            ->getQuery()
            ->getResult();
                    
    }


    public  function searchBySName($phrase,$field){

        $string = "^$phrase.*.$";

        $sql = "select v.".$field." as phrase from design2visitor as d 
                inner join visitor as v on v.id = d.visitor_id 
                inner join file as f on f.id = d.file_id 
                inner join type_visitor as tv on tv.id = v.type_visitor_id 
                inner join document as dc on dc.id = v.type_doc_id 
                where v.".$field." REGEXP '".$string."'";

        $connection =  $this->_em->getConnection();

         return $result = $connection->query($sql)->fetchAll();

    }


}
