main_page:
    path: /
    defaults: { _controller: AppBundle:Default:index }

edit_page:
    path: /edit/{id}
    defaults: { _controller: AppBundle:Default:edit }
    requirements:
          id: \d+

404_page:
    path: /404
    defaults: { _controller: AppBundle:Default:notFound }

ajax_search:
    path: /ajax-search
    defaults: {_controller: AppBundle:Ajax:ajaxSearch}

csv_export:
    path: /export/
    defaults: {_controller: AppBundle:Export:export}

login:
    path: /login/
    defaults: {_controller: AppBundle:Authentication:login}

search:
    path: /search/
    defaults: {_controller: AppBundle:Search:search}

admin_form:
    path: /admin/
    defaults: {_controller: AppBundle:Admin:admin}

logout:
    path: /logout/
    defaults: {_controller: AppBundle:Authentication:logout}

log:
    path: /log/
    defaults: {_controller: AppBundle:Su:Log}

log_export:
    path: /log-export/
    defaults: {_controller: AppBundle:Su:logExport}

ogame:
  path: /ogame/
  defaults: {_controller: AppBundle:Ogame:Test}


