main_page:
    path: /
    defaults: { _controller: AppBundle:Default:index }

edit_page:
    path: /edit/{id}
    defaults: { _controller: AppBundle:Default:edit }
    requirements:
          id: \d+

404_page:
    path: /404
    defaults: { _controller: AppBundle:Default:notFound }

ajax_search:
    path: /ajax-search
    defaults: {_controller: AppBundle:Default:ajaxSearch}

csv_export:
    path: /export/
    defaults: {_controller: AppBundle:Default:export}

login:
    path: /login/
    defaults: {_controller: AppBundle:Default:login}

search:
    path: /search/
    defaults: {_controller: AppBundle:Default:search}

admin_form:
    path: /admin/
    defaults: {_controller: AppBundle:Default:admin}

logout:
    path: /logout/
    defaults: {_controller: AppBundle:Default:logout}


