# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value
services:
     user_keep:
       class: AppBundle\DependencyInjection\UserManager\UserKeeper
       arguments: ['@doctrine.orm.entity_manager','@session']

     export_service:
       class: AppBundle\DependencyInjection\ExportService\ExportService
     search_service:
       class: AppBundle\DependencyInjection\SearchService\SearchService
       arguments: ['@doctrine.orm.entity_manager']